import Foundation

/// Rewrites a decoded `BlockClipboardPayload` into brand-new rows ready to
/// insert into a target document — the paste half of `tasks/NO-010.md`
/// §3.2 ("다른 문서에 붙여넣기 시 재작성 항목"), mirrored by
/// `CrossBlockSelectionClipboardSerializer`'s copy half.
///
/// Kept as a pure function over already-decoded payload data (no
/// `UIPasteboard`/Core Data touched here) so it's directly unit-testable,
/// same rationale as the serializer's own doc comment.
/// `DetailViewModel+CrossBlockSelectionPaste.swift` is the only caller
/// that decodes a real pasteboard and persists the result.
enum CrossBlockSelectionPasteRewriter {
    /// One paste's worth of already-rewritten model rows, ready for a
    /// caller to persist and insert into in-memory state.
    struct Result {
        let items: [DocumentItem]
        let textContents: [TextContent]
        let listGroups: [ListGroup]
        let textMarks: [TextMark]
    }

    /// Rewrites every array in `payload` for pasting into
    /// `targetDocumentId` (`tasks/NO-010.md` §3.2):
    /// - Every item gets a fresh `id` (common invariant 5, never reusing
    ///   the original) and one of `orderKeys` — already generated by the
    ///   caller (via `OrderKey.between`, positioned relative to the
    ///   target document's existing items) one-to-one with
    ///   `payload.items`, in the same order.
    /// - `documentId` is rewritten to `targetDocumentId` on every item and
    ///   every newly created `ListGroup` — the same rewrite for a
    ///   same-document paste (C1, where `targetDocumentId` just happens to
    ///   equal the source) and a cross-document paste (C2).
    /// - `depth` is copied as-is (no remapping needed — it's a relative
    ///   nesting level, not a position, `tasks/NO-009.md` §3.1), EXCEPT the
    ///   whole pasted range is shifted down by `payload.items.first`'s own
    ///   depth, so the first item lands at depth 0 if it didn't start
    ///   there while every other item keeps its original depth
    ///   *difference* from that first item (common invariant 7/C3). This
    ///   assumes `payload.items` is already in document order — true for
    ///   every payload `CrossBlockSelectionClipboardSerializer` produces,
    ///   since "first item" only means anything under that assumption.
    /// - `listGroupId`: every old group id actually referenced by a pasted
    ///   item is assigned exactly ONE freshly created `ListGroup` (common
    ///   invariant 6 — shared members never split across groups), using
    ///   that old group's own `listType` looked up from
    ///   `payload.listGroups` (falling back to the item's own `textKind`,
    ///   which uses the same vocabulary, if that lookup somehow misses).
    /// - `textMarks` follow their owning item's new id; a mark whose item
    ///   isn't part of this paste at all is dropped.
    ///
    /// - Precondition: `orderKeys.count == payload.items.count`.
    static func rewrite(
        payload: BlockClipboardPayload,
        targetDocumentId: String,
        orderKeys: [String]
    ) -> Result {
        let idByOriginalId = Dictionary(uniqueKeysWithValues: payload.items.map { ($0.id, UUID().uuidString) })

        var groupAssigner = ListGroupAssigner(payload: payload, targetDocumentId: targetDocumentId)
        let newItems = rewriteItems(
            payload: payload, idByOriginalId: idByOriginalId, orderKeys: orderKeys, groupAssigner: &groupAssigner
        )
        let newTextContents = rewriteTextContents(payload: payload, idByOriginalId: idByOriginalId)
        let newTextMarks = rewriteTextMarks(payload: payload, idByOriginalId: idByOriginalId)

        return Result(
            items: newItems,
            textContents: newTextContents,
            listGroups: groupAssigner.createdGroups,
            textMarks: newTextMarks
        )
    }

    /// `payload.items`, each given its fresh id (from `idByOriginalId`),
    /// `targetDocumentId`, a depth clamped/shifted relative to the first
    /// item (common invariant 7/C3), one of `orderKeys`, and a
    /// `listGroupId` resolved through `groupAssigner`.
    private static func rewriteItems(
        payload: BlockClipboardPayload,
        idByOriginalId: [String: String],
        orderKeys: [String],
        groupAssigner: inout ListGroupAssigner
    ) -> [DocumentItem] {
        let depthShift = payload.items.first?.depth ?? 0
        return payload.items.enumerated().compactMap { index, original in
            guard let newId = idByOriginalId[original.id] else { return nil }
            let newListGroupId = original.listGroupId.map {
                groupAssigner.resolvedGroupId(forOldGroupId: $0, original: original)
            }
            return DocumentItem(
                id: newId,
                documentId: groupAssigner.targetDocumentId,
                depth: max(0, original.depth - depthShift),
                listGroupId: newListGroupId,
                contentType: original.contentType,
                orderKey: orderKeys[index]
            )
        }
    }

    /// `payload.textContents`, each re-keyed onto its item's fresh id — a
    /// mark/content whose owning item isn't part of this paste at all
    /// (`idByOriginalId` lookup miss) is dropped.
    private static func rewriteTextContents(
        payload: BlockClipboardPayload, idByOriginalId: [String: String]
    ) -> [TextContent] {
        payload.textContents.compactMap { original in
            guard let newId = idByOriginalId[original.itemId] else { return nil }
            return TextContent(
                itemId: newId,
                textKind: original.textKind,
                plainText: original.plainText,
                headingLevel: original.headingLevel,
                alignment: original.alignment,
                isChecked: original.isChecked,
                customStyleId: original.customStyleId
            )
        }
    }

    private static func rewriteTextMarks(
        payload: BlockClipboardPayload, idByOriginalId: [String: String]
    ) -> [TextMark] {
        payload.textMarks.compactMap { original in
            guard let newItemId = idByOriginalId[original.itemId] else { return nil }
            return TextMark(
                itemId: newItemId,
                startOffset: original.startOffset,
                endOffset: original.endOffset,
                markType: original.markType,
                valueMode: original.valueMode,
                valueText: original.valueText
            )
        }
    }

    /// Assigns each pasted item its new `listGroupId`, creating exactly
    /// ONE fresh `ListGroup` per distinct old group id actually referenced
    /// (common invariant 6) rather than one per item.
    private struct ListGroupAssigner {
        let targetDocumentId: String
        private let listTypeByOldGroupId: [String: String]
        private let textKindByOriginalId: [String: String]
        private var newGroupByOldGroupId: [String: ListGroup] = [:]
        private(set) var createdGroups: [ListGroup] = []

        init(payload: BlockClipboardPayload, targetDocumentId: String) {
            self.targetDocumentId = targetDocumentId
            listTypeByOldGroupId = Dictionary(uniqueKeysWithValues: payload.listGroups.map { ($0.id, $0.listType) })
            textKindByOriginalId = Dictionary(
                uniqueKeysWithValues: payload.textContents.map { ($0.itemId, $0.textKind) }
            )
        }

        /// The new group id `oldGroupId` maps to, creating that group the
        /// first time it's seen. `original` is only consulted for its own
        /// `textKind` as a fallback `listType` source, if `oldGroupId`
        /// doesn't resolve via `payload.listGroups` (shouldn't normally
        /// happen — defensive only).
        mutating func resolvedGroupId(forOldGroupId oldGroupId: String, original: DocumentItem) -> String {
            if let existingGroup = newGroupByOldGroupId[oldGroupId] {
                return existingGroup.id
            }
            let listType = listTypeByOldGroupId[oldGroupId]
                ?? textKindByOriginalId[original.id]
                ?? TextItemKind.bulletedListItem
            let newGroup = ListGroup(documentId: targetDocumentId, listType: listType)
            newGroupByOldGroupId[oldGroupId] = newGroup
            createdGroups.append(newGroup)
            return newGroup.id
        }
    }
}
